import type { User, Order, Stream, SupportTicket } from "./types";

// ─── Users ─────────────────────────────────────────────────────

export const seedUsers: User[] = [
  {
    id: "usr_001",
    username: "sneakerhead99",
    displayName: "Jordan Miles",
    email: "jordan.m@email.com",
    role: "buyer",
    status: "active",
    balance: 342.5,
    creditBalance: 0,
    joinedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "usr_002",
    username: "sellerX",
    displayName: "Marcus Chen",
    email: "marcus.c@email.com",
    role: "seller",
    status: "active",
    balance: 8_420.0,
    creditBalance: 0,
    joinedAt: "2023-11-02T08:30:00Z",
  },
  {
    id: "usr_003",
    username: "vintagequeen",
    displayName: "Priya Sharma",
    email: "priya.s@email.com",
    role: "seller",
    status: "active",
    balance: 5_130.75,
    creditBalance: 25.0,
    joinedAt: "2024-01-20T14:15:00Z",
  },
  {
    id: "usr_004",
    username: "funko_king",
    displayName: "Tyler Brooks",
    email: "tyler.b@email.com",
    role: "buyer",
    status: "active",
    balance: 89.0,
    creditBalance: 15.0,
    joinedAt: "2024-06-10T09:45:00Z",
  },
  {
    id: "usr_005",
    username: "cardshark_mike",
    displayName: "Mike Rossi",
    email: "mike.r@email.com",
    role: "seller",
    status: "warned",
    balance: 12_750.0,
    creditBalance: 0,
    joinedAt: "2023-08-05T16:20:00Z",
  },
  {
    id: "usr_006",
    username: "luxbags_liz",
    displayName: "Elizabeth Tran",
    email: "liz.t@email.com",
    role: "seller",
    status: "active",
    balance: 22_300.0,
    creditBalance: 0,
    joinedAt: "2023-06-18T11:00:00Z",
  },
  {
    id: "usr_007",
    username: "mod_sarah",
    displayName: "Sarah Kim",
    email: "sarah.k@liveloot.internal",
    role: "admin",
    status: "active",
    balance: 0,
    creditBalance: 0,
    joinedAt: "2023-01-10T08:00:00Z",
  },
  {
    id: "usr_008",
    username: "ops_manager_j",
    displayName: "James Rodriguez",
    email: "james.r@liveloot.internal",
    role: "admin",
    status: "active",
    balance: 0,
    creditBalance: 0,
    joinedAt: "2022-09-01T08:00:00Z",
  },
];

// ─── Streams ───────────────────────────────────────────────────

export const seedStreams: Stream[] = [
  {
    id: "str_001",
    sellerUsername: "sellerX",
    title: "🔥 Heat Check — Jordan Retros & Dunks",
    category: "Sneakers",
    status: "live",
    viewerCount: 847,
    items: [
      { name: 'Jordan 4 Retro "Bred Reimagined"', currentBid: 285.0, sold: false },
      { name: "Nike Dunk Low Panda", currentBid: 110.0, sold: true },
      { name: 'Air Jordan 1 High OG "Chicago Lost & Found"', currentBid: 190.0, sold: false },
      { name: "New Balance 550 White Green", currentBid: 95.0, sold: true },
    ],
    startedAt: "2026-08-14T19:00:00Z",
  },
  {
    id: "str_002",
    sellerUsername: "vintagequeen",
    title: "Y2K Vintage Haul — Rare Finds Only 💎",
    category: "Vintage Clothing",
    status: "live",
    viewerCount: 312,
    items: [
      { name: "Vintage Coogi Sweater XL", currentBid: 145.0, sold: false },
      { name: "90s Tommy Hilfiger Windbreaker", currentBid: 78.0, sold: true },
      { name: "Deadstock FUBU Jersey", currentBid: 120.0, sold: false },
    ],
    startedAt: "2026-08-14T18:30:00Z",
  },
  {
    id: "str_003",
    sellerUsername: "sellerX",
    title: "Funko Pop Grails — Marvel & DC Exclusives",
    category: "Funko Pops",
    status: "live",
    viewerCount: 523,
    items: [
      { name: "Funko Pop Venom #234 (Glow Chase)", currentBid: 65.0, sold: false },
      { name: "Funko Pop Spider-Man #03 (Metallic)", currentBid: 320.0, sold: false },
      { name: "Funko Pop Batman #01 (Blue Metallic)", currentBid: 185.0, sold: true },
      { name: "Funko Pop Deadpool #20 (Metallic)", currentBid: 42.0, sold: true },
      { name: "Funko Pop Iron Man #04 (Glow)", currentBid: 275.0, sold: false },
    ],
    startedAt: "2026-08-14T20:00:00Z",
  },
  {
    id: "str_004",
    sellerUsername: "cardshark_mike",
    title: "Pokemon TCG — Base Set & Modern Hits",
    category: "Trading Cards",
    status: "ended",
    viewerCount: 0,
    items: [
      { name: "Charizard Base Set Holo (PSA 7)", currentBid: 1_250.0, sold: true },
      { name: "Pikachu Illustrator Promo (LP)", currentBid: 890.0, sold: true },
      { name: "Lugia Neo Genesis 1st Ed (PSA 8)", currentBid: 675.0, sold: true },
    ],
    startedAt: "2026-08-14T15:00:00Z",
  },
];

// ─── Orders ────────────────────────────────────────────────────

export const seedOrders: Order[] = [
  {
    id: "ord_001",
    buyerUsername: "sneakerhead99",
    sellerUsername: "sellerX",
    itemName: "Nike Dunk Low Panda",
    amount: 110.0,
    status: "completed",
    streamId: "str_001",
    createdAt: "2026-08-14T19:15:00Z",
  },
  {
    id: "ord_002",
    buyerUsername: "funko_king",
    sellerUsername: "sellerX",
    itemName: "Funko Pop Batman #01 (Blue Metallic)",
    amount: 185.0,
    status: "disputed",
    streamId: "str_003",
    createdAt: "2026-08-14T20:22:00Z",
  },
  {
    id: "ord_003",
    buyerUsername: "sneakerhead99",
    sellerUsername: "vintagequeen",
    itemName: "90s Tommy Hilfiger Windbreaker",
    amount: 78.0,
    status: "completed",
    streamId: "str_002",
    createdAt: "2026-08-14T18:45:00Z",
  },
  {
    id: "ord_004",
    buyerUsername: "funko_king",
    sellerUsername: "sellerX",
    itemName: "Funko Pop Deadpool #20 (Metallic)",
    amount: 42.0,
    status: "completed",
    streamId: "str_003",
    createdAt: "2026-08-14T20:10:00Z",
  },
  {
    id: "ord_005",
    buyerUsername: "sneakerhead99",
    sellerUsername: "cardshark_mike",
    itemName: "Charizard Base Set Holo (PSA 7)",
    amount: 1_250.0,
    status: "disputed",
    streamId: "str_004",
    createdAt: "2026-08-14T16:30:00Z",
  },
  {
    id: "ord_006",
    buyerUsername: "funko_king",
    sellerUsername: "cardshark_mike",
    itemName: "Pikachu Illustrator Promo (LP)",
    amount: 890.0,
    status: "completed",
    streamId: "str_004",
    createdAt: "2026-08-14T16:45:00Z",
  },
  {
    id: "ord_007",
    buyerUsername: "sneakerhead99",
    sellerUsername: "sellerX",
    itemName: "New Balance 550 White Green",
    amount: 95.0,
    status: "refunded",
    streamId: "str_001",
    createdAt: "2026-08-14T19:30:00Z",
  },
  {
    id: "ord_008",
    buyerUsername: "funko_king",
    sellerUsername: "luxbags_liz",
    itemName: "Coach Tabby Shoulder Bag (Chalk)",
    amount: 395.0,
    status: "pending",
    streamId: "str_002",
    createdAt: "2026-08-14T18:55:00Z",
  },
  {
    id: "ord_009",
    buyerUsername: "sneakerhead99",
    sellerUsername: "cardshark_mike",
    itemName: "Lugia Neo Genesis 1st Ed (PSA 8)",
    amount: 675.0,
    status: "completed",
    streamId: "str_004",
    createdAt: "2026-08-14T17:00:00Z",
  },
  {
    id: "ord_010",
    buyerUsername: "funko_king",
    sellerUsername: "vintagequeen",
    itemName: "Vintage Coogi Sweater XL",
    amount: 145.0,
    status: "pending",
    streamId: "str_002",
    createdAt: "2026-08-14T19:10:00Z",
  },
  {
    id: "ord_011",
    buyerUsername: "sneakerhead99",
    sellerUsername: "sellerX",
    itemName: 'Funko Pop Venom #234 (Glow Chase)',
    amount: 65.0,
    status: "pending",
    streamId: "str_003",
    createdAt: "2026-08-14T20:35:00Z",
  },
  {
    id: "ord_012",
    buyerUsername: "funko_king",
    sellerUsername: "sellerX",
    itemName: 'Funko Pop Iron Man #04 (Glow)',
    amount: 275.0,
    status: "disputed",
    streamId: "str_003",
    createdAt: "2026-08-14T20:40:00Z",
  },
];

// ─── Support Tickets ───────────────────────────────────────────

export const seedTickets: SupportTicket[] = [
  {
    id: "tkt_001",
    reporterUsername: "funko_king",
    targetUsername: "sellerX",
    orderId: "ord_002",
    type: "dispute",
    status: "open",
    priority: "high",
    description:
      "Received Batman Funko Pop with damaged box. Seller listed as mint condition. Requesting full refund.",
    createdAt: "2026-08-14T20:45:00Z",
  },
  {
    id: "tkt_002",
    reporterUsername: "sneakerhead99",
    targetUsername: "cardshark_mike",
    orderId: "ord_005",
    type: "fraud_report",
    status: "open",
    priority: "critical",
    description:
      "Charizard PSA 7 arrived but looks like a PSA 5 in a re-sealed case. Possible counterfeit grading label. Paid $1,250.",
    createdAt: "2026-08-14T17:30:00Z",
  },
  {
    id: "tkt_003",
    reporterUsername: "funko_king",
    targetUsername: "sellerX",
    orderId: "ord_012",
    type: "dispute",
    status: "open",
    priority: "medium",
    description:
      "Iron Man Funko Pop auction ended before I could confirm bid. Seller ended stream early.",
    createdAt: "2026-08-14T20:50:00Z",
  },
  {
    id: "tkt_004",
    reporterUsername: "mod_sarah",
    targetUsername: "cardshark_mike",
    type: "complaint",
    status: "in_progress",
    priority: "high",
    description:
      "Multiple fraud reports against this seller in the last 30 days. Internal review flagged suspicious grading patterns.",
    createdAt: "2026-08-14T18:00:00Z",
  },
  {
    id: "tkt_005",
    reporterUsername: "sneakerhead99",
    targetUsername: "vintagequeen",
    orderId: "ord_003",
    type: "complaint",
    status: "resolved",
    priority: "low",
    description:
      "Windbreaker arrived with minor stain not shown in photos. Seller offered partial refund of $15. Accepted.",
    createdAt: "2026-08-14T19:00:00Z",
  },
  {
    id: "tkt_006",
    reporterUsername: "funko_king",
    targetUsername: "luxbags_liz",
    orderId: "ord_008",
    type: "dispute",
    status: "open",
    priority: "medium",
    description:
      "Order has been pending for 3 days with no shipping update. Seller hasn't responded to messages.",
    createdAt: "2026-08-14T19:30:00Z",
  },
];
